steps:
  # Create the .env file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "VISION_AI_API_URL=${_VISION_AI_API_URL}" > .env.production && \
        echo "GATEWAY_API_URL=${_GATEWAY_API_URL}" >> .env.production && \
        echo "MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}" >> .env.production  && \
        echo "DISCORD_WEBHOOK_ID" >> .env.production && \
        echo "DISCORD_WEBHOOK_TOKEN" >> .env.production
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/super-app:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/super-app:$COMMIT_SHA"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/super-app=gcr.io/$PROJECT_ID/super-app:$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "prod.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    args:
      - "run"
      - "--filename=prod.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/super-app:$COMMIT_SHA"